name: Codacy Coverage for CloudFormation Templates (CFT)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-coverage:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install Dependencies
        run: |
          pip install yamllint  # Install yamllint for YAML linting

      # Step 3: Run YAML Lint
      - name: Run YAML Lint
        run: |
          yamllint templates/ --format json > linting-report.json  # Lint all YAML files and output as JSON

      # Step 4: Upload linting results to Codacy using API
      - name: Upload Linting Report to Codacy
        run: |
          curl -X POST "https://api.codacy.com/2.0/coverage" \
            -H "Authorization: token ${{ secrets.CODACY_PROJECT_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data @linting-report.json
