name: Codacy Analysis with Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codacy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Run Codacy Analysis
    - name: Run Codacy Analysis
      uses: codacy/codacy-analysis-cli-action@v4
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}

    # Install dependencies and run tests with coverage (example for Python)
    - name: Install Dependencies
      run: |
        #pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run Tests with Coverage
      run: |
        pytest --cov=codeacycft --cov-report=xml  # Replace with your module name

    # Download Codacy Coverage Reporter
    - name: Download Codacy Coverage Reporter
      run: |
        curl -Ls https://github.com/codacy/codacy-coverage-reporter/releases/latest/download/codacy-coverage-reporter-assembly.jar -o codacy-coverage-reporter.jar

    # Upload Coverage Report to Codacy
    - name: Upload Coverage Report to Codacy
      run: |
        java -jar codacy-coverage-reporter.jar report \
          --coverage-reporter-path coverage.xml  # Use the coverage file generated by pytest
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
