name: Codacy Coverage for CloudFormation Templates (CFT)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-coverage:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install Dependencies
        run: |
          pip install yamllint  # Install yamllint for YAML linting

      # Step 3: Run YAML linting
      - name: Run YAML Lint
        run: |
          yamllint templates/ --format parsable > coverage-report.txt  # Lint all YAML files in the templates directory

      # Step 4: Download Codacy Coverage Reporter
      - name: Download Codacy Coverage Reporter
        run: |
          curl -Ls https://github.com/codacy/codacy-coverage-reporter/releases/latest/download/codacy-coverage-reporter-assembly.jar -o codacy-coverage-reporter.jar

      # Step 5: Upload Coverage Report to Codacy (for YAML lint results)
      - name: Upload Coverage Report to Codacy
        run: |
          java -jar codacy-coverage-reporter.jar report \
            --language yaml \
            --file coverage-report.txt  # Upload the lint results
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}  # Ensure this is set in GitHub Secrets
