---
name: Codacy and Code Coverage for CloudFormation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codacy-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          pip install taskcat boto3

      - name: Validate CloudFormation Templates
        run: |
          yamllint templates/

      - name: Test CloudFormation Templates with Taskcat
        run: |
          taskcat test run

      - name: Deploy CloudFormation (Optional for Coverage)
        run: |
          aws cloudformation deploy \
            --template-file templates/vpc.yaml \
            --stack-name my-stack \
            --region us-east-1

      - name: Generate Coverage Report
        run: python scripts/coverage.py > coverage.lcov

      - name: Upload Coverage to Codacy
        run: |
          curl -Ls https://github.com/codacy/codacy-coverage-reporter/releases/latest/download/codacy-coverage-reporter-assembly.jar -o codacy-coverage-reporter.jar
          java -jar codacy-coverage-reporter.jar report -l Python -r coverage.lcov
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
